name: Build + test + release

on:
  push:
    branches:
      - '*'
      
    tags:
      - "*"
  pull_request:

jobs:
  unit_test:
    name: Golang Unit Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.19.3"]
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go mod download
        shell: bash
      - run: VALIDATOR_PRIVATE_KEY=31b571bf6894a248831ff937bb49f7754509fe93bbd2517c9c73c4144c0e97dc go test ./plugin/evm/... -test.v 
        shell: bash